### ISSUE TITLE
Pintar paredes y techo

### ISSUE THREAD

**Issue by ivanmr200** [ivanmr200/enunciado_02_cocina#13]

**Comment by DaniMr21** [comment]
Antes de pintar, el suelo debe estar colocado y luego protegido con papel

**Comment by DaniMr21** [comment]
![Captura](https://github.com/ivanmr200/enunciado_02_cocina/assets/154756435/2c925c11-5a7e-46a5-a0e6-e5e1fd173f40)
![Captura](https://github.com/ivanmr200/enunciado_02_cocina/assets/154756435/23991148-83f7-41bf-ba78-bccd2921a50f)
