### ISSUE TITLE
Nueva instalación eléctrica

### ISSUE THREAD

**Issue by ivanmr200** [ivanmr200/enunciado_02_cocina#15]
Nuevas luces, focos, enchufes...

**Comment by DaniMr21** [comment]
Total: 9 focos small LED ref: 12345678 + recolocación posterior de la lámpara anterior

**Comment by nereayi** [comment]
![image](https://github.com/ivanmr200/enunciado_02_cocina/assets/162732302/b050e1d0-ab6d-415e-be60-bf34daf6902f)

**Comment by DaniMr21** [comment]
![image](https://github.com/ivanmr200/enunciado_02_cocina/assets/154756435/ea4ed89f-f33a-483c-bf3c-8f240d853f67)
Lampara puesta en su sitio
