### ISSUE TITLE
Nueva instalación de fontanería

### ISSUE THREAD

**Issue by ivanmr200** [ivanmr200/enunciado_02_cocina#16]
Cambiar tuberías, grifos ....

**Comment by DaniMr21** [comment]
No iniciar la obra antes de haber cerrado las llaves de paso y haber notificado a los vecinos

**Comment by nereayi** [comment]
![image](https://github.com/ivanmr200/enunciado_02_cocina/assets/162732302/2380c973-90aa-45c0-a442-c385630e9d08)

**Comment by DaniMr21** [comment]
hecho
