### ISSUE TITLE
Completar fontanería

### ISSUE THREAD

**Issue by ivanmr200** [ivanmr200/enunciado_02_cocina#23]
Poniendo grifos nuevos, nueva pila...

**Comment by DaniMr21** [comment]
Una vez hecho esto, ya se podrán abrir las llaves de paso

**Comment by nereayi** [comment]
Se ha colocado el grifo, para el que se ha hecho uso de una rosca nueva.

**Comment by nereayi** [comment]
![image](https://github.com/ivanmr200/enunciado_02_cocina/assets/162732302/75e3618d-cb61-4a28-820e-2b1c682e9360)
