### ISSUE TITLE
Reunión con clientes

### ISSUE THREAD

**Issue by ivanmr200** [ivanmr200/enunciado_02_cocina#8]
Comentar presupuesto final, el diseño realizado previamente, el tiempo que se tardará, etc, y confirmar el inicio de la reforma

**Comment by DaniMr21** [comment]
Dado que la empresa escogida es "Reformas Montecillo" y ya tenemos los precios, creo que lo mejor será optar por el plan medio, ya que es el que mejor se adapta a nuestro presupuesto, el plan alto se va mucho de presupuesto y el bajo no satisface nuestras pretensiones
